try:
    print(x)
except:
    print("something is wrong")
finally:
    print("try-except is over")